import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar/Navbar'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prueba Next Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://unpkg.com/flowbite@1.4.0/dist/flowbite.js"></script>
      </head>


      <body className={inter.className}>
        <Navbar />
        {children}


      </body>

    </html>
  );
}
